version: '3'


# global environmental variables
env:
  DEBUG: 1

tasks:
  default:
    deps: [build, test]
    desc: Builds and tests all components

  help:
    cmds:
      - cmd: echo "Run .bin/mail binary in order to get inbox counts your gmail accounts"
        silent: true

  # build project
  build:
    desc: Builds the project
    cmds:
      - cmd: echo "Building ..."
        silent: true
      - cmd: go build -o ./bin/mail ./cmd/main.go

  # test project
  test:
    desc: Tests project
    cmds:
      - cmd: echo "Testing project"
        silent: true
      - cmd: gotest -p 1 -count=1 -cover -coverprofile=unit.coverage.out ./...

  # start project
  start:
    desc: Run mail
    cmds:
      - task: build
        silent: true
      - cmd: ./bin/mail
